on: [push, pull_request]

name: Contracts
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      working-directory: contracts
      dojo_version: v0.3.3
    steps:
      - name: Install dojoup
        run: curl -L https://install.dojoengine.org | bash

      - name: Install dojo
        run: /home/runner/.config/.dojo/bin/dojoup --version ${{ env.dojo_version }}

      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1

      - name: Check format
        working-directory: ${{env.working-directory}}
        run: scarb fmt --check

      - name: Run cairo tests
        working-directory: ${{env.working-directory}}
        run: /home/runner/.config/.dojo/bin/sozo test

      - name: Build
        working-directory: ${{env.working-directory}}
        run: /home/runner/.config/.dojo/bin/sozo build

      - name: Start katana
        run: /home/runner/.config/.dojo/bin/katana --disable-fee &

      - name: Deploy
        working-directory: ${{env.working-directory}}
        run: /home/runner/.config/.dojo/bin/sozo migrate --name World
